### ISSUE TITLE
FreeBSD: add tor_alpha support (again)

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#115]
We removed tor_alpha support for FreeBSD on 2015-07-22 because security/tor-devel was not regularly updated.
https://github.com/nusenu/ansible-relayor/commit/595c8637d73920b7192ba1ffdb14f46c85dddbdb

tor-devel is currently at the latest tor alpha release, but the security/tor-devel package is unlike security/tor lacking multi-instance support. Once upstream adds multi-instance support add tor_alpha support.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217319

it is easy:
```
- name: Select devel package if tor_alpha is enabled (FreeBSD)
  set_fact:
    tor_packages: tor-devel
  when: tor_alpha == True
```
