### ISSUE TITLE
Error when trying to run createdir on FreeBSD 11.0-RELEASE

### ISSUE THREAD

**Issue by duelle** [nusenu/ansible-relayor#126]
Hi,
I am trying to get my feet wet with using ansible in general and the ansible-relayor.
When I tried to create the directories for a Tor-Relay, I ran the following command:
```ansible-playbook my_playbook.yml -t createdir -i inventory -l vserv3```

And got this error message:
```
PLAY [tor-relays] *****************************************************************************

TASK [Gathering Facts] ************************************************************************
ok: [vserv3]

TASK [nusenu.relayor : setup IP list (1/2)] ***************************************************
fatal: [vserv3]: FAILED! => {"failed": true, "msg": "{{ v6tmp[0:ipv4_count|int]|ipv6('address') }}: Unexpected templating type error occurred on ({{ v6tmp[0:ipv4_count|int]|ipv6('address') }}): 'bool' object has no attribute '__getitem__'"}
```

With `vserv3` being in the `tor-relays` group and the `my_playbook.yml` looking like this:
```
- hosts: tor-relays
  vars:
    tor_signingkeylifetime_days: 90
    tor_nickname: "{{ ansible_bostname }}"
    tor_offline_masterkey_dir: ~/tmp/ansible/tor-offline-masterkeys
  roles:
    - nusenu.relayor
```

The remote host is running FreeBSD 11.0-RELEASE.
**Edit: It has a public IPv4 address, but no IPv6 address**

My local machine is running Ansible in version: 2.3.0.0
If there is any further information I can provide, please let me know.

For me this looks like being related to #80 but as I read that there should/would be a workaround in place, I thought it might make sense to report this. In case I missed something I would be happy for a hint on how to fix this.

Thank you a lot for your work!
