### ISSUE TITLE
add HardenedBSD to kitchen platforms once bento builds our packer file

### ISSUE THREAD

**Issue by nusenu** [nusenu/ansible-relayor#155]
https://github.com/chef/bento/pull/1008
https://app.vagrantup.com/boxes/search?provider=virtualbox&q=hardenedbsd&sort=downloads&utf8=%E2%9C%93

**Comment by cheeseplus** [comment]
<3 https://app.vagrantup.com/bento/boxes/hardenedbsd-11

**Comment by nusenu** [comment]
Seth Thomas:
> <3 https://app.vagrantup.com/bento/boxes/hardenedbsd-11

thanks for building it,
but it appears we have a problem with kitchen here (vagrant up works fine).

kitchen create t-guard-hardenedbsd-11


Couldn't open file ansible-relayor/.kitchen/kitchen-vagrant/t-guard-hardenedbsd-11/hardenedbsd-11
and see the kitchen backtrace in .kitchen/logs/kitchen.log

**Comment by Lirt** [comment]
If you don't explicitly define used Vagrant box in platforms, Kitchen does not replace it to `bento/` repository. I don't know why it does not do it right now.

You can check it using `grep "vm\.box" .kitchen/kitchen-vagrant/t-exit-hardenedbsd-11/Vagrantfile`.

```ruby
c.vm.box = "hardenedbsd-11"
```

So if you define platform like following block and run `kitchen test hardenedbsd-11`, it works fine:

```yaml
- name: hardenedbsd-11
  driver:
    box: bento/hardenedbsd-11
    provision: True
    vagrantfiles:
      - test/vagrant_provisions/freebsd_vagrant_provision.rb
```

Notice it still needs to install python, but installation is same as for freebsd.
