### ISSUE TITLE
Update OrPort doesn't delete the old tor instance

### ISSUE THREAD

**Issue by tsekityam** [nusenu/ansible-relayor#218]
**Describe the bug**

**To Reproduce**
I ran the playbook with the following config
```yaml
---
- hosts: relays
  vars:
    tor_ContactInfo: email:kytse[]protonmail.com url:kytse.com proof:uri-rsa pgp:8685bcbd0506582c65f6887dda88f181771752f9 donationurl:https://github.com/sponsors/tsekityam ciissversion:2

  roles:
    - nusenu.relayor
```
And I had two tor instance running on port 9000 and 9100

Then I want to change the ports to 443 and 80, so I change the config and run
```yaml
---
- hosts: relays
  vars:
    tor_ContactInfo: email:kytse[]protonmail.com url:kytse.com proof:uri-rsa pgp:8685bcbd0506582c65f6887dda88f181771752f9 donationurl:https://github.com/sponsors/tsekityam ciissversion:2
    tor_enableControlSocket: true
    tor_ports:
      - { orport: 80, dirport: 0 }
      - { orport: 443, dirport: 0 }

  roles:
    - nusenu.relayor
```
Now I got 4 tor instances, running on port 80, 443, 9000 and 9100.

I tried reboot the server, and all 4 instances are autostarted.

**Expected behavior**
I expect there are only two tor intances on port 80 and 443. The instances on port 9000 and 9100 should be deleted. 

**Version information (please include the following information):**
- ansible [core 2.11.3] 
- ansible-relayor version (Don't know how to get)

**Playbook information**
Inclued in To *Reproduce*

**OS information**
macOS 11.5.2

**Debug information**
Please add the output of your `ansible-playbook` run using "-vvv".
